routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', 'HomeController@index');

Auth::routes();

Route::get('/albums/{album}/image', 'AlbumController@image');
Route::get('/client/{url?}/{url2?}/{url3?}', 'ClientController')->name('client');
Route::get('/home', 'HomeController@index');
// Route::get('/settings', 'UserController@settings')->name('settings');
Route::get('/tracks/{track}/audio', 'TrackController@audio');
Route::get('/settings/edit', 'SettingController@edit')->name('settings.edit');

Route::put('/settings', 'SettingController@update')->name('settings.update');

Route::resource('albums', 'AlbumController');
Route::resource('artists', 'ArtistController');
Route::resource('tracks', 'TrackController');
Route::resource('settings', 'SettingController', ['only' =>
    ['index']
]);
Route::resource('user', 'UserController');

resources/views/client.blade.php
@extends('layouts.app')

@section('styles')
<style>
    .column-left {
        padding-left: 0px;
        margin-left: 0px;
        height: 100%;
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        /*padding-bottom: 8vh;*/
        /*padding-top: 4vh;*/
    }
</style>
@endsection

@section('content')
<div class="container scrollspy" id="content" style="width: 100%; height: 100%; padding-left: 0px;">
    <!-- <div class="row" style="width: 100%; height: 100%;"> -->
        <div class="col-md-2 scrollspy" style="height: 100%; padding-left: 0px; padding-top: 6vh; padding-bottom: 8vh;">
            <div class="column-left" data-spy="affix" style="width: 16vw; padding-top: 0px; height: 86vh;">
                <column></column>
                <track-info></track-info>
                <!-- <div style="">
                    <img src="/img/noalbum.svg" style="width: 100%;"></img>
                    <div style="height: 8vh; border-right: 1px solid;"></div>
                </div> -->
            </div>
        </div>
        <div class="col-md-10" style="margin-top: 8vh; margin-bottom: 8vh;">
            <!-- <component v-bind:is="getView()"></component> -->
            <router-view></router-view>
        </div>
    <!-- </div> -->
</div>
<bar-player></bar-player>
@endsection

resources/views/home.blade.php
@extends('ajax')

<div class="container" id="content">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">User Dashboard</div>
                <div class="panel-body">

                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">Albums</div>
                <div class="panel-body">
                    <a class="btn btn-primary" href="{{ route('albums.index') }}">More Albums</a>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">Tracks</div>
                <div class="panel-body">
                    <a class="btn btn-primary" href="{{ route('tracks.index') }}">More Tracks</a>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/home.template.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/settings.blade.php
@extends('layouts.form')

@section('content')
<div class="container" id="content">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">User Settings</div>
                <div class="panel-body" id="formpanel">
                    <form class="form-horizontal" id="userform" role="form" method="POST" v-on:submit="cancel">
                        {{ csrf_field() }}

                        <input name="id" type="text" value="{{ $user->id }}" style="display: none;"></input>
                        <text-input name="email" label="Email" value="{{ $user->email }}"></text-input>
                        <password-input name="password" label="Password" hint="Leave blank to remain unchanged"></password-input>
                        <submit-button btn-style="btn-success" method="PUT" form="userform" url="{{ route('user.update', $user->id) }}" label="Update"><submit-button>
                    </form>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">Application Settings</div>
                <div class="panel-body">
                    @if (Session::get('status') == '200-settings')
                        <div class="alert alert-success">
                            Settings updated successfully!
                        </div>
                    @endisset
                    <p>These are the settings used for what every user sees on the website.</p>
                    <form class="form-horizontal" role="form" method="POST" action="{{ route('settings.update') }}"
                        enctype="multipart/form-data">
                        {{ csrf_field() }}
                        {{ method_field('PUT') }}
                        <text-input label="Format" name="format" required value="{{ $errors->has('format') ? old('format') : $format }}"></text-input>
                        </text-input>
                        <text-input label="Bitrate" name="bitrate" required value="{{ $errors->has('bitrate') ? old('bitrate') : $bitrate }}"></text-input>
                        <submit-button btn-style="btn-primary" label="Update"></submit-button>
                    </form>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">API Authentication</div>
                <div class="panel-body">
                    <passport-clients></passport-clients>
                    <passport-authorized-clients></passport-authorized-clients>
                    <passport-personal-access-tokens></passport-personal-access-tokens>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection