routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', 'HomeController@index');

Auth::routes();

Route::get('/albums/{album}/image', 'AlbumController@image');
Route::get('/client/{url?}/{url2?}/{url3?}', 'ClientController')->name('client');
Route::get('/home', 'HomeController@index');
// Route::get('/settings', 'UserController@settings')->name('settings');
Route::get('/tracks/{track}/audio', 'TrackController@audio');
Route::get('/settings/edit', 'SettingController@edit')->name('settings.edit');

Route::put('/settings', 'SettingController@update')->name('settings.update');

Route::resource('albums', 'AlbumController');
Route::resource('artists', 'ArtistController');
Route::resource('tracks', 'TrackController');
Route::resource('settings', 'SettingController', ['only' =>
    ['index']
]);
Route::resource('user', 'UserController');

app/Album.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Album extends Model
{
    protected $fillable = [
        'artist_id', 'name', 'path'
    ];

    public function artist()
    {
        return $this->belongsTo('App\Artist');
    }

    public function genres()
    {
        return $this->belongsToMany('App\Genre');
    }

    public function tracks()
    {
        return $this->belongsToMany('App\Track');
    }
}

app/Http/Controllers/AlbumController.php
<?php

namespace App\Http\Controllers;

use App\Album;
use App\Artist;
use App\Track;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;

class AlbumController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $albums = Album::all();
        $albums->load('artist');
        return $albums;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $artists = Artist::all();
        return view('album/create', ['artists' => $artists]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if ($request->has('quicksave'))
        {
            $album = Album::create(['name' => $request->name]);
        }
        else
        {
            $path = $request->file->store('albums');
            $album = Album::create([
                'name' => $request->name,
                'path' => $path,
                'artist_id' => $request->artist
            ]);
            return ['status' => 'success'];
        }
        return ['status' => 'success', 'id' => $album->id];
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Album  $album
     * @return \Illuminate\Http\Response
     */
    public function show(Album $album)
    {
        $album->load('artist');
        $album->load('tracks');
        $album->tracks->load('artists');
        return $album;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Album  $album
     * @return \Illuminate\Http\Response
     */
    public function edit(Album $album)
    {
        $tracks = Track::all();
        $artists = Artist::all();
        return view('album/edit', ['album' => $album, 'artists' => $artists, 'tracks' => $tracks]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Album  $album
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Album $album)
    {
        if ($request->hasFile('file')) {
            Log::info('File detected. Updating album artwork...');
            if (Storage::disk('local')->exists($album->path)) {
                Log::info('Old file detected. Deleting old artwork...');
                Storage::delete($album->path);
            }
            $path = $request->file->store('albums');
            $album->path = $path;
        }
        Log::info('Updating artist information...');
        $album->name = $request->name;
        $album->artist_id = $request->artist;
        $album->save();

        return ['status' => 'success'];
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Album  $album
     * @return \Illuminate\Http\Response
     */
    public function destroy(Album $album)
    {
        Storage::delete($album->path);
        $album->tracks()->detach();
        $album->delete();
        return ['status' => 'OK'];
    }

    // Additional functions.

    /**
     * Gets the image file for the requested album.
     *
     * @param  \App\Album $album
     * @return \Illuminate\Http\Response
     */
    public function image(Album $album)
    {
        if (Storage::disk('local')->exists($album->path))
        {
            $size = Storage::size($album->path);
            return response(Storage::get($album->path))->withHeaders([
                'Content-Disposition' => 'filename=image.jpeg',
                'Content-Length' => $size,
                'Content-Type' => 'image/jpeg'
            ]);
        } else
        {
            return redirect('/img/noalbum.svg');
        }
    }

    public function getTracks(Album $album)
    {

    }
}

resources/views/album/create.blade.php
@extends('layouts.form')

@section('content')
<div class="container" id="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2" id="column">
            <div class="panel panel-default">
                <div class="panel-heading">New Album</div>
                <div class="panel-body" id="formpanel">
                    <form class="form-horizontal" id="userform" role="form" method="POST" v-on:submit="cancel">
                        {{ csrf_field() }}

                        <file-input label="Image" name="file"></file-input>

                        <text-input name="name" label="Name"></text-input>
                        <select-input name="artist" label="Artist" type="artists"></select-input>
                        <submit-button btn-style="btn-success" label="Create" url="{{ route('albums.store') }}" method="POST" form="userform" file=""></submit-button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/album/edit.blade.php
@extends('layouts.form')

@section('content')
<div class="container" id="container" style="margin-top: 8vh;">
    <div class="row">
        <div class="col-md-8 col-md-offset-2" id="column">
            <div class="panel panel-default">
                <div class="panel-heading">{{ $album->name }}</div>
                <div class="panel-body" id="formpanel">
                    <form class="form-horizontal" id="updateform" role="form" method="POST" v-on:submit="cancel">
                        {{ csrf_field() }}

                        <div class="form-group">
                            <label for="image" class="col-md-4 control-label">New Image</label>

                            <div class="col-md-6">
                                <input id="file" type="file"></input>
                            </div>
                        </div>

                        <text-input label="name" name="name" value="{{$album->name}}"></text-input>
                        <select-input label="Artist" name="artist" type="artists" value="{{$album->artist}}"></select-input>

                        <submit-button btn-style="btn-success" form="updateform" label="Update" method="PUT" url="{{ route('albums.update', $album->id) }}"></submit-button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection