routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', 'HomeController@index');

Auth::routes();

Route::get('/albums/{album}/image', 'AlbumController@image');
Route::get('/client/{url?}/{url2?}/{url3?}', 'ClientController')->name('client');
Route::get('/home', 'HomeController@index');
// Route::get('/settings', 'UserController@settings')->name('settings');
Route::get('/tracks/{track}/audio', 'TrackController@audio');
Route::get('/settings/edit', 'SettingController@edit')->name('settings.edit');

Route::put('/settings', 'SettingController@update')->name('settings.update');

Route::resource('albums', 'AlbumController');
Route::resource('artists', 'ArtistController');
Route::resource('tracks', 'TrackController');
Route::resource('settings', 'SettingController', ['only' =>
    ['index']
]);
Route::resource('user', 'UserController');

app/Track.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Track extends Model
{
    //
    protected $fillable = [
        'title', 'path',
    ];

    public function albums()
    {
        return $this->belongsToMany('App\Album');
    }

    public function artists()
    {
        return $this->belongsToMany('App\Artist');
    }

    public function genres()
    {
        return $this->belongsToMany('App\Genre');
    }

    public function playlists()
    {
        return $this->belongsToMany('App\Playlist');
    }
}

app/Http/Controllers/TrackController.php
<?php

namespace App\Http\Controllers;

use App\Album;
use App\Artist;
use App\Setting;
use App\Track;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;

class TrackController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tracks = Track::all();
        $tracks->load('artists');
        $tracks->load('albums');
        return $tracks;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $albums = Album::all();
        $artists = Artist::all();
        return view('track/create', ['albums' => $albums, 'artists' => $artists]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $path = $request->file->store('tracks');
        $track = Track::create([
            'title' => $request->title,
            'path' => $path,
        ]);
        $artists = Artist::find($request->artists);
        $albums = Album::find($request->albums);
        $track->albums()->saveMany($albums);
        $track->artists()->saveMany($artists);
        return ['status' => 'success'];
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Track  $track
     * @return \Illuminate\Http\Response
     */
    public function show(Track $track)
    {
        $track->load('albums');
        $track->load('artists');
        return $track;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Track  $track
     * @return \Illuminate\Http\Response
     */
    public function edit(Track $track)
    {
        $albums = Album::all();
        $artists = Artist::all();
        return view('track/edit', ['albums' => $albums, 'artists' => $artists, 'track' => $track]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Track  $track
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Track $track)
    {
        $track->title = $request->title;
        $albums = Album::find($request->albums);
        $track->albums()->detach();
        $track->albums()->saveMany($albums);
        $artists = Artist::find($request->artists);
        $track->artists()->detach();
        $track->artists()->saveMany($artists);
        $track->save();
        return ['status' => 'success'];
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Track  $track
     * @return \Illuminate\Http\Response
     */
    public function destroy(Track $track)
    {
        Storage::delete($track->path);
        $track->artists()->detach();
        $track->delete();
        return ['status' => 'OK'];
    }

    // Additional functions.

    /**
     * Gets the audio file for the requested track.
     *
     * @param  \App\Track $track
     * @return \Illuminate\Http\Response
     */
    public function audio(Track $track)
    {
        $ffmpeg = config('app.ffmpeg');
        abort_unless(is_executable($ffmpeg), 500, 'Please make sure that ffmpeg is configured correctly.');

        $format = Setting::firstOrCreate(['id' => 'format'], ['value' => 'ogg'])->value;
        $bitrate = Setting::firstOrCreate(['id' => 'bitrate'], ['value' => 128])->value;


        $args = [
            '-i '.escapeshellarg(storage_path().DIRECTORY_SEPARATOR.'app'.DIRECTORY_SEPARATOR.$track->path),
            '-map 0:0',
            '-v 0',
            "-ab {$bitrate}k",
            "-f {$format}",
            '-'
        ];

        header('Content-Type: audio/'.$format);
        header('Content-Disposition: attachment; filename="'.basename($track->path).'"');

        passthru("$ffmpeg ".implode($args, ' '));

        // return response()->file(storage_path().DIRECTORY_SEPARATOR.'app'.DIRECTORY_SEPARATOR.$track->path);
    }

    public function queue()
    {
        $tracks = Track::all();
        return ['tracks' => $tracks];
    }
}

resources/views/track/create.blade.php
@extends('layouts.form')
<script src="{{ asset('js/jsmediatags.min.js') }}"></script>

@section('content')
<div class="container" id="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2" id="column">
            <file-handler></file-handler>
        </div>
    </div>
</div>
@endsection

resources/views/track/edit.blade.php
@extends('layouts.form')

@section('content')
<div class="container" id="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2" id="column">
            <div class="panel panel-default">
                <div class="panel-heading">{{$track->title}}</div>
                <div class="panel-body" id="formpanel">

                    <form class="form-horizontal" id="updateform" role="form" method="POST" v-on:submit="cancel">
                        {{ csrf_field() }}

                        <div class="form-group">
                            <label for="Track" class="col-md-4 control-label">Track</label>

                            <div class="col-md-6">
                                <audio controls src="/tracks/{{$track->id}}/audio"></audio>
                            </div>
                        </div>
                        <text-input label="Title" name="title" value="{{$track->title}}"></text-input>

                        <select-input label="Artists" multiple="true" name="artists[]" type="artists" value="{{$track->artists}}"></select-input>
                        <select-input label="Albums" multiple="true" name="albums[]" type="albums" value="{{$track->albums}}"></select-input>

                        <submit-button btn-style="btn-success" form="updateform" label="Update" method="PUT" url="/tracks/{{$track->id}}">
                        </submit-button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/track/index.blade.php
@extends('layouts.index')

@section('actions')
    <a class="btn btn-primary" href="{{ route('tracks.create') }}">Upload Tracks</a>
    <a class="btn btn-success queue" href="{{ route('tracks.queue') }}">Queue</a>
@endsection

@section('heading')
    Tracks
@endsection

@section('columns')
    <th>ID</th>
    <th>Title</th>
    <th>Artists</th>
    <th>View</th>
    <th>Edit</th>
@endsection

@section('rows')
    @foreach ($tracks as $track)
        <tr>
            <td>{{$track->id}}</td>
            <td>{{$track->title}}</td>
            <td>
                @foreach($track->artists as $artist)
                    {{$artist->name}}
                @endforeach
            </td>
            <td><button class="btn btn-success" onclick="play('{{ $track->id }}')">Play</button></td>
            <td><a class="btn btn-primary" href="/tracks/{{$track->id}}/edit">Edit</a></td>
        </tr>
    @endforeach
@endsection